// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verity.CashFlow.Infrastructure.Persistence;

#nullable disable

namespace Verity.CashFlow.Infrastructure.Migrations
{
    [DbContext(typeof(CashFlowContext))]
    partial class CashFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verity.CashFlow.Domain.Entities.Cash", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("ClosedBalanceInCents")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfCash")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<long>("StartBalanceInCents")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Cashes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfCash = new DateOnly(2023, 9, 9),
                            IsClosed = false,
                            StartBalanceInCents = 1000000L
                        });
                });

            modelBuilder.Entity("Verity.CashFlow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountInCents")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CashId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfTransaction")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashId");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("45301e31-bed5-4695-87b0-286c2b4b495b"),
                            AmountInCents = 1500L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "2 milks",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("025b9bc8-5cce-4a22-98f2-ce6727a0f482"),
                            AmountInCents = 5000L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "10 rice",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("732d6158-f1c7-4c12-adcb-9f3fac617fa2"),
                            AmountInCents = 3000L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "20 salt",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("f22c362d-6a21-440a-9cb0-5a1aa63a106e"),
                            AmountInCents = 2515L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "1 Kg argentine apple",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e564b9e8-a62f-42eb-9dfd-c6f25e5e5816"),
                            AmountInCents = 65750L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "15 Kg picanha",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("988a5a5a-06e6-4cf7-b43e-571beb55ed13"),
                            AmountInCents = 20000L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "Energy Bill",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("936203f8-74dd-42cc-841c-c8ec340e16d9"),
                            AmountInCents = 10000L,
                            CashId = new Guid("35b5b1cc-56b5-4e61-97d5-12ea4d0f72e5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfTransaction = new DateOnly(2023, 9, 9),
                            Description = "Water Bill",
                            Status = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Verity.CashFlow.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Verity.CashFlow.Domain.Entities.Cash", "Cash")
                        .WithMany("Transactions")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cash");
                });

            modelBuilder.Entity("Verity.CashFlow.Domain.Entities.Cash", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
